config :

  exp_type : optunafinetuning
 
  dataProcessorOpts :
    type : melSpectrogram
    seconds : 5
    sr : 32000
    n_mels : 224
    hop_length : 716
  
  # classesDict : None

  classes :  #12 birds with the fewest recordings
    - nilfly2 
    - rutfly6 
    - scamin3
    - bncwoo3
    - wbbfly1  
    - pomgrp2  
    - inpher1  
    - blaeag1  
    - darter2 
    - integr 
    - asiope1 
    - niwpig1 

  # classes :
  # - blrwar1
  # - houspa
  # - grewar3
  # - commyn
  # - hoopoe
  # - comros
  # - eucdov
  # - bkwsti
  # - barswa
  # - graher1
  # - bcnher
  # - lirplo

  dataLoaderOpts : 
    # type : PreTrainingDataLoader 
    type : ClassificationDataLoader #ClassificationDataLoader NewClassificationDataLoader
    batchSize : 96
    ratioTrainTestCalib : 
      - 0.8
      - 0.2
      - 0.
    # dataPath : C:/Users/fares/OneDrive/Bureau/kaggleBirds/data/BirdClef2024/unlabeled_soundscapes/
    dataPath : C:/Users/fares/OneDrive/Bureau/kaggleBirds/data/BirdClef2024/train_audio/
    dtype : torch.float32
    extractionDone : False 
    byFileExtraction : True

  pretrainedModelOpts :
    type : ULite
    pretrainedModelPath : C:/Users/fares/OneDrive/Bureau/kaggleBirds/models/BirdClef2024/pretrainedModel3/epoch_4

  # modelOpts :
  #   type : ULite
  #   lr : 0.001
  #   step_size : 5
  #   gamma : 0.8
  #   nEpochs : 100
  #   optimizer : Adam
  #   criterion : MSELoss
  #   use_gpu : True

  modelOpts :
    type : ClassifierForULite
    lr : 0.001
    step_size : 1
    gamma : 0.9
    nEpochs : 10
    optimizer : Adam
    criterion : CrossEntropyLoss
    use_gpu : True

  expOpts :
    # savingPath : C:/Users/fares/OneDrive/Bureau/kaggleBirds/models/BirdClef2024/pretrainedmodel3/
    savingPath : C:/Users/fares/OneDrive/Bureau/kaggleBirds/models/BirdClef2024/finetunedModel4/
    loggingPath : None

  optunaParams0 :
    reduction_factor : 2
    min_early_stopping_rate : 1
    n_trials : 30
    timeout : 14400
  
  optunaParams1 :
    reduction_factor : 2
    min_early_stopping_rate : 2
    n_trials : 30
    timeout : 7200
  
  optunaParams2 :
    reduction_factor : 2
    min_early_stopping_rate : 2
    n_trials : 100
    timeout : 3600




    